#ifndef QPY_CLEANUP_H
#define QPY_CLEANUP_H
#undef dict_for_each_call_method
#undef dict_for_each_set_ent_
#undef dict_cmp_for_each_set_ent_
#undef dict_for_each_
#undef dict_for_each_mask_
#undef dict_for_each_probe
#undef dict_cmp_for_each_set_ent
#undef dict_for_each_mask
#undef dict_for_each
#undef dict_for_each_set_ent
#undef dict_vst_get_group_index
#undef dict_vst_get_mm_group
#undef dict_vst_get_index
#undef dict_vst_get_mask
#undef dict_vst_next_mask
#undef dict_vst_get_kh
#undef dict_vst_get_key
#undef dict_vst_get_hash
#undef dict_vst_get_value
#endif //QPY_CLEANUP_H
