#ifndef QPY_VISIT_H
#define QPY_VISIT_H

/**
 * @dict_for_each_*: visit every set entry in a dict and do things within the loop body just like a `for` block. Typically, they perform `for_each_set_entries_in_groups: do {...}`
 *
 * Warning: The @dict_for_each* set of macros are defined for convenience and are not intended for any use beyond this file. For iteration, use @dict_iter* functions.
 */

/**
 * @dict_for_each_call_method: The generic call macro  with default values/functions needed for the rest of the `dict_for_each*` macros
 * @parameters: @meth (the macro to call); @v (see @visit_t); non-default arguments are passed as vargs and handled by the called  macro.
 * The @___*___ names are variables to be defined in the loop; their names are what you get by removing the underscores and qpy. The default values it passes are described below:
 * @v
 * @j: a variable to store indices during visitation
 * @mask: a variable to store mask generated by @cmp
 * @mm_test* (or @cmp: generate mask for nonempty entries in a group
 * @next_group (does current_group_index += NGROUP)
 * @p: probe index
 * @k: probe counter
 * @g: save initial group index before visit (probe)
 * @dict_slot: returns the probed slot index
 * @probe_next_dict_slot
 */
#define dict_for_each_call_method(mth, v, ...)          \
    mth((v),                                            \
        ___qpyj___,   ___qpymask___, mm_test_has_entry, \
        mm_scan_mask, NEXT_GROUP,  ___qpyp___,          \
        ___qpyk___,   ___qpyg___,  dict_slot,           \
        probe_next_dict_slot,      __VA_ARGS__          \
       )

/**
 * @dict_for_each_set_ent: visit every set entry in the mask generated by @cmp.
 * Note: it is only used within @dict_for_each and @dict_for_each_mask block
 */
#define dict_for_each_set_ent_(v, j, m, cmp, scan, ...)         \
    for (mask_t m=(v.mm=mm_load(v.grp+v.i), cmp(v.mm)); (m) AND (j=scan(m)+v.i); m &= m - 1)

/**
 * @dict_for_each_cmp_set_ent: main block for @dict_for_wach_cmp: compares each group with an @mmx group and generates a mask; visit every set entry in each generated mask.
 *  Note: it is only used under its top block @dict_for_each_cmp.
 */
#define dict_cmp_for_each_set_ent_(v, j, m, _c, scan, _t, _p, _k, _g, _s, _n, cmp2, xmm, ...) \
    for (mask_t m=(v.mm=mm_load(v.grp+v.i), cmp2(v.mm, xmm)); (m) AND (j=scan(m)+v.i); m &= m - 1)

/** @dict_for_each: visit every set entry in dict */
#define dict_for_each_(v, j, m, cmp, scan, next, ...)   \
    for (size_t j=0; (v.i < v.size); next(v.i)) \
        dict_for_each_set_ent_(v, j, m, cmp, scan)

/**
 * @dict_for_each_mask: visit every set entry in dict
 * mask is handled externally and must be set to zero or call @dict_for_each_next_mask before it can visit the next group else it loops infinitely
 */
#define dict_for_each_mask_(v, j, m, cmp, _s, next, ...) \
    for (size_t j=0; (v.i < v.size); next(v.i))\
        for (mask_t m=(v.mm=mm_load(v.grp+v.i), cmp(v.mm)); m;)

/**
 * @dict_for_each_cmp: the top block for @dict_for_each_cmp_set_ent; visits entries by probing.
 * It can be called independent of its main block though (an infinte loop trap)
 */ 
#define dict_for_each_probe(v, j, m, _c, _s, _n, p, k, g, slot, next_slot, ...) \
    for (size_t p=0, k=0, j=0, g=v.i; (1); v.i=slot(p, g, v.size), next_slot(p, k))

/* The below macros are defined for convenient call to the above macros */
#define dict_for_each_probe(v) dict_for_each_call_meth(dict_for_each_, v)
#define dict_cmp_for_each_set_ent(v, x) dict_for_each_call_meth(dict_for_each_cmp_set_ent_, v, mm_test_equal, x)
#define dict_for_each_mask(v) dict_for_each_call_meth(dict_for_each_mask_, v)
#define dict_for_each(v) dict_for_each_call_meth(dict_for_each_, v)
#define dict_for_each_set_ent(v) dict_for_each_call_meth(dict_for_each_set_ent_, v)
#define dict_for_each_next_mask()  (___qpymask___=0)

/* The below macros are to access common properties within the dict_for_each* block through the visit struct */
#define dict_vst_get_group_index(v) ((v).i)
#define dict_vst_get_mm_group(v)    ((v).mm)
#define dict_vst_get_index(v) (___qpyj___)
#define dict_vst_get_mask(v)  (___qpymask___)
#define dict_vst_get_kh(v)    ((v).kh[__qpyj__])
#define dict_vst_get_key(v)   ((v).kh[__qpyj__].key)
#define dict_vst_get_hash(v)  ((v).kh[__qpyj__].hash)
#define dict_vst_get_value(v) ((v).val[__qpyj__])

#endif
